# https://docs.haskellstack.org/en/stable/yaml_configuration/

ghc-options:
  # -fllvm -pgmlo opt37 -pgmlc llc37 -pgma clang40 -pgmc clang40 
  "*": "-split-sections -optc-Wno-expansion-to-defined -pgml cc -optl-fuse-ld=lld"

apply-ghc-options: everything
